
const frasesArtefactoES = [
  "desestabiliza",
  "sobrecargados",
  "ametralladoras",
  "desestabilizan",
  "agota",
  "sobrecargadas",
  "los objetivos agotados infligen menos daño",
  "perfora escudos",
  "fusiles de francotirador",
  "campeones de barrera",
  "agotan",
  "amplificaciòn",
  "carga fulminante",
  "arco",
  "vacío",
  "proyectiles volátiles",
  "orbe de poder",
  "maraña",
  "atadura",
  "proyectiles deshilachadores",
  "fusiles de rastreo",
  "marañas mutilación",
  "ametralladores",
  "gujas",
  "disrupción",
  "agotamiento",
  "mutilación",
  "agotado",
  "multilado",
  "cegadora",
  "cinéticas",
  "súper",
  "componente elemental",
  "lanzacohetes",
  "remate",
  "volatilidad",
  "debilitante",
  "amplificación",
  "deshilachados",
  "bestia de hebras",
  "fusiles de fusión",
  "fusiles de fusión lineal",
  "mutilados",
  "granadas",
  "cuerpo a cuerpo",
  "sacude",
  "debilitados",
  "agotados",
  "deshilachan",
  "mutilado",
  "malla trenzada"
]

export default frasesArtefactoES;