
const frasesES = [
  "silencio y borras",
  "silencio",
  "borrasca",
  "tormenta de estasis",
  "ralentiza esquiarla de estasis",
  "shuriken de estasis",
  "ralentizarlos",
  "ralentizar",
  "granada glaciar",
  "granada crepuscular",
  "granada de ola de frío",
  "dardo de cuerda",
  "gancho",
  "mutila",
  "energía cuerpo a cuerpo",
  "cogerlo",
  "deshilacha",
  "atadura",
  "suspende",
  "suspensión",
  "bestias de hebras",
  "suspendidos",
  "energía de habilidad de clase",
  "malla trenzada",
  "maraña",
  "proyectiles deshilachadores",
  "habilidad de granada",
  "remates",
  "mutilación",
  "energía de granada",
  "deshilachado",
  "mayor duración",
  "granada adicional",
  "maraña de gancho",
  "movimiento aéreo",
  "habilidad de clase",
  "deshilachadores",
  "luz",
  "oscuridad",
  "cinético",
  "trascendencia",
  "prismática",
  "regeneración de energía de granada",
  "prolonga la duración",
  "solar",
  "calcinante",
  "incrementador elemental",
  "cinéticas",
  "energía de trascendencia",
  "súper",
  "aliados cercanos",
  "arco",
  "solares",
  "vacío",
  "trascendencia de oscuridad",
  "trascendencia de luz",
  "granadas",
  "proyectiles volátiles",
  "cuerpo a cuerpo potenciados",
  "trasciendes",
  "orbes de poder",
  "componente elemental",
  "suprimir",
  "esquirla de estasis",
  "brecha de vacío",
  "impactos",
  "radiante",
  "golpes finales",
  "radiantes",
  "vacío debilitan",
  "sacuden",
  "regeneración de salud",
  "carga fulminante",
  "restauración",
  "cristal de estasis",
  "congelas",
  "igniciones solares",
  "vara de estasis",
  "fragmenta",
  "cura de forma continua",
  "fuerte control direccional",
  "fuerte aumento inicial de velocidad",
  "velocidad y control direccional moderados",
  "ralentiza a los objetivos",
  "congelan",
  "torreta de estasis",
  "ralentizadores",
  "agujas trenzadas",
  "posarán",
  "granada de grilletes",
  "granada de bestias de hebras",
  "cuerpo a cuerpo con gancho",
  "consumir",
  "trance de los tejedores",
  "bestias de hebras posadas",
  "marañas",
  "los golpes finales con bestias de hebras",
  "esquivar",
  "aire",
  "resistencia al daño",
  "suprime",
  "guantelete de estasis",
  "ataque de convulsión",
  "esprinta",
  "fragmentarlos",
  "gran barrera",
  "cubierto",
  "atrae el fuego enemigo",
  "fuerte impulso inicial",
  "hace retroceder a los objetivos",
  "coloca un explosivo de estasis retardado",
  "cristales de estasis",
  "bloquear el daño",
  "congelar objetivos",
  "lanza de estasis",
  "hojas entrelazadas",
  "velocidad de ataque",
  "fuerte tajo ascendente",
  "mutilarlos",
  "velocidad de regeneración del cuerpo a cuerpo",
  "barricada",
  "derribar a los objetivos cercanos",
  "estandarte de guerra",
  "cura",
  "espada",
  "cargarán",
  "aumenta la frecuencia",
  "ancla de vacío",
  "debilita",
  "trampas",
  "mayor alcance",
  "duran más",
  "cuchillas de vacío",
  "velo de sombras",
  "energía de súper",
  "debilitan",
  "volatilidad",
  "invisibilidad",
  "devorar",
  "exploten",
  "regeneración de tu salud",
  "movilidad",
  "se recargará",
  "agachado",
  "bomba de humo",
  "vórtice",
  "se adhiere a cualquier superficie",
  "emite",
  "dañino",
  "muro horizontal",
  "habilidades",
  "divide",
  "múltiples explosiones",
  "adhiere",
  "explota dos veces",
  "proyectiles",
  "persiguen",
  "caída en picado",
  "nube de humo",
  "invisibles",
  "invisible",
  "debilitamiento",
  "supresión",
  "debilitante",
  "velocidad de recarga",
  "estabilidad",
  "sacudida",
  "daga electrificada",
  "fugacidad",
  "rastro iónico",
  "resistencia",
  "recuperación",
  "amplificación",
  "cegadora",
  "cegado",
  "teletransporte",
  "daño cuerpo a cuerpo",
  "ciego",
  "ciega",
  "ráfaga de energía",
  "igniciones",
  "arma dorada",
  "ardan",
  "espíritu de fuego",
  "calcinación",
  "calcinas",
  "eficacia en el aire",
  "calcinados",
  "ardiendo",
  "arma dorada: tiro a la cabeza",
  "arma dorada: tirador",
  "lluvia de cuchillas",
  "cuchillo arrojadizo",
  "ignición",
  "proyectil explosivo",
  "radio de detonación",
  "bomba nova",
  "daña de forma continuada",
  "erupción letal de vacío",
  "rastrea",
  "proyectiles rastreadores más pequeños",
  "aumenta el daño de las armas",
  "aleja",
  "volátil",
  "explora dos veces",
  "sobrecargar",
  "granada de vórtice",
  "proyectil de axiones",
  "granada de dispersión",
  "granada magnética",
  "habilidad de vacío",
  "más salud",
  "grieta",
  "alma de vacío",
  "debilitándolo",
  "energía cuerpo a cuerpo y de granada",
  "salud",
  "alma de arco",
  "teletransportarte hacia delante",
  "cegados",
  "rastros iónicos",
  "torreta",
  "relámpagos encadenados",
  "cegar",
  "calcinar",
  "poderosa aura",
  "proyectiles adicionales",
  "calcinadora",
  "canción flamígera",
  "calcinarán",
  "aumento térmico",
  "energía solar",
  "esquivar una vez más",
  "curas",
  "disparar armas",
  "usar tu cuerpo a cuerpo",
  "lanzar granadas",
  "planeas",
  "los golpes finales mientras se está en el aire",
  "duración",
  "granadas de fusión",
  "de curación",
  "ígneas",
  "granada de curación",
  "curación",
  "granada solar",
  "granda ígnea",
  "granda de fusión",
  "mortero solar",
  "lanzamiento de escudo",
  "muro defensivo",
  "proteger",
  "cúpula indestructible",
  "amparo del alba",
  "sobreescudo de vacío",
  "hachas de vacío",
  "debilitándolos",
  "recoger",
  "hacha de vacío",
  "debilitar",
  "pequeña barrera",
  "apuntas",
  "aumenta la velocidad de recarga, la estabilidad y el alcance de las armas",
  "escudo de vacío",
  "esprintar",
  "explosión frontal",
  "regenere",
  "amplíe",
  "explote",
  "granadas cegadoras, de pulsos, relámpago",
  "tormenta",
  "granada cegadora",
  "destello cegador",
  "granada de pulsos",
  "granada relámpago",
  "granada tormenta",
  "nube de tormenta itinerante",
  "escudo frontal",
  "tanto tu daño cuerpo a cuerpo como tu alcance",
  "armas",
  "mazo llameante",
  "dañar a los objetivos cercanos",
  "ciclón de llamas",
  "martillo de sol",
  "puntos solares",
  "calcinado"
]

export default frasesES;