
const frasesArtefactoMX = [
    "aturde",
    "sobrecargados",
    "ametralladoras",
    "agota",
    "sobrecargadas",
    "los objetivos exhaustos infligen daño saliente reducido",
    "perforan escudos",
    "aturden a",
    "los fusiles de francotirador",
    "campeones de barrera",
    "amplificación",
    "carga de rayo",
    "de arco",
    "de vacío",
    "proyectiles volátiles",
    "orbe de poder",
    "maraña",
    "proyectiles destramadores",
    "fusil de rastreo",
    "rasgar",
    "marañas",
    "gujas",
    "interrumpirán",
    "agotarán",
    "agotamiento",
    "agotado",
    "rasgado",
    "arco",
    "cegadora",
    "cinética",
    "super",
    "objeto elemental",
    "lanzacohetes",
    "remates",
    "volatilidad",
    "vacío",
    "debilitante",
    "destramadores",
    "hilarachas",
    "agotados",
    "rasgados",
    "súper",
    "ametralladora pesada",
    "granada",
    "cuerpo a cuerpo",
    "electrocuta",
    "debilitados",
    "destrama",
    "malla tejida"
]

export default frasesArtefactoMX;