
const frasesMX = [
    "agacharte",
    "agujas tejidas",
    "alcance mejorado",
    "aliados cercanos",
    "amparo del alba",
    "amplifica",
    "amplificación",
    "ancla de vacío",
    "apuntar",
    "armadura gélida",
    "arma dorada",
    "arma dorada - tiro a la cabeza",
    "arma dorada - tirador",
    "armas",
    "arrojar granadas",
    "atrapalo",
    "atraparlo",
    "atrae el fuego hostil",
    "aumenta el daño de las armas",
    "aumenta la frecuencia",
    "aumenta la velocidad de recarga, la estabilidad y el alcance del arma",
    "aumento térmico",
    "avanzar con fugacidad",
    "barricada",
    "bloquean daño",
    "bomba de humo",
    "bomba nova",
    "busca",
    "buscan",
    "calcina",
    "calcinación",
    "calcinados",
    "calcinados ignición",
    "calcinan",
    "calcinar",
    "calcinas",
    "carga de rayo",
    "cargan",
    "cegar",
    "cegadora",
    "cegados",
    "ciega",
    "ciega",
    "cinético",
    "cinéticas",
    "corta ascendente pesado",
    "cristal de estasis",
    "cubierto",
    "cuchilla de vacío",
    "cuchillas tejidas",
    "cuchillo arrojadizo",
    "cuerpo a cuerpo",
    "cuerpo a cuerpo potenciados",
    "cuerpos a cuerpo",
    "cura",
    "cura de forma continua",
    "curan",
    "curas",
    "daga electrificada",
    "daño",
    "daño cuerpo a cuerpo",
    "daño de precisión",
    "dardo de cuerdas",
    "debilita",
    "debilitado",
    "debilitados",
    "debilitan",
    "debilitante",
    "destello cegador",
    "destrama",
    "destraman",
    "destramado",
    "destramadores",
    "detonación",
    "devorar",
    "disparar armas",
    "domo indestructible",
    "duración",
    "duran más",
    "electriza",
    "electrizado",
    "electrizados",
    "electrizan",
    "electrizante",
    "emite",
    "emperchan",
    "empuja",
    "empuja a los objetivos",
    "energía cuerpo a cuerpo",
    "energía de granada",
    "energía de habilidad de clase",
    "energía de trascendencia",
    "energía solar",
    "en el aire",
    "erupción letal de vacío",
    "esprintar",
    "esquivar",
    "estabilidad",
    "estandarte de guerra",
    "estasis",
    "estás en el aire",
    "evadir",
    "evasión adicional",
    "explosión frontal",
    "explota dos veces",
    "exploten",
    "extiende",
    "extiende su duración",
    "fragmenta",
    "fragmento de estasis",
    "fragmentos de estasis",
    "frecuencia",
    "fuerte aumento inicial de velocidad",
    "fuerte control direccional",
    "fuerte impulso inicial",
    "gancho",
    "gancho cuerpo a cuerpo",
    "granada",
    "granada adicional",
    "granada cegadora",
    "granada curativa",
    "granada de campo crepuscular",
    "granada de cadenas",
    "granada de desublimación",
    "granada de dispersión",
    "granada de fusión",
    "granada de hilarachas",
    "granada de proyectiles ígneos",
    "granada de pulsos",
    "granada de vórtice",
    "granada glaciar",
    "granada magnética",
    "granada relámpago",
    "granada solar",
    "granada tormenta",
    "granadas",
    "granadas cegadoras, de pulsos, relámpago y tormenta",
    "granadas de fusión, curativas, solares",
    "gran barrera",
    "golpe escalofriante",
    "golpes",
    "golpes finales",
    "golpes finales al estar en el aire",
    "grieta",
    "guantelete de estasis",
    "habilidad de clase",
    "habilidad de granada",
    "habilidad de vacío",
    "hachas de vacío",
    "hilaracha",
    "hilarachas",
    "hilarachas emperchadas",
    "igniciones",
    "igniciones solares",
    "inflige daño",
    "inflige daño constante",
    "invisibilidad",
    "invisibles",
    "lanzamiento de escudo",
    "lanza de estasis",
    "lluvia de cuchillas",
    "luz",
    "malla tejida",
    "maraña",
    "maraña de enganche",
    "marañas",
    "martillo del sol",
    "mayor altura",
    "mayor duración",
    "moderados",
    "mortero solar",
    "movilidad",
    "movimiento aéreo",
    "munición destramadora",
    "muro defensivo",
    "muro horizontal",
    "nube de humo",
    "objeto elemental",
    "orbe de poder",
    "orbes de poder",
    "oscuridad",
    "pequeña barrera",
    "persiguen",
    "planeas",
    "poder",
    "potenciación elemental",
    "prismática",
    "proyectil de axiones",
    "proyectil explosivo",
    "proyectiles adicionales",
    "proyectiles ígneos",
    "proyectiles rastreadores",
    "proyectiles volátiles",
    "puntos solares",
    "radio de la detonación",
    "radiante",
    "radiantes",
    "rasga",
    "rasgarlos",
    "rasgas",
    "rastros iónicos",
    "rayos",
    "recoger",
    "recuperación",
    "recuperar",
    "recarga",
    "recarga tu arma",
    "recarga tu habilidad cuerpo a cuerpo",
    "regeneración cuerpo a cuerpo",
    "regeneración de energía de granada",
    "regeneración de salud",
    "remates",
    "resistencia",
    "resistencia al daño",
    "restauración",
    "restauración, cura",
    "ruptura de vacío",
    "se adhiere a cualquier superficie",
    "shuriken de estasis",
    "silencia",
    "silencio",
    "silencio y ventisca",
    "sobrecargar tu granada",
    "sobreescudo",
    "sobreescudo de vacío",
    "solar",
    "solares",
    "soles",
    "supresión",
    "suprime",
    "suprimen",
    "suprimir",
    "suspendido",
    "suspendidos",
    "suspende",
    "suspender",
    "suspensión",
    "teletransportarse",
    "teletransportarte",
    "te transportas",
    "tercer salto",
    "tormenta de estasis",
    "tormenta móvil",
    "torreta",
    "torreta de estasis",
    "trampas",
    "trance del tejedor",
    "trascendencia",
    "trascendencia de luz",
    "trascendencia de oscuridad",
    "tritura",
    "triturar",
    "triturarse",
    "trituras",
    "usa",
    "vacío",
    "vacío debilitan",
    "vara de estasis",
    "varas",
    "velo de sombras",
    "velocidad de ataque",
    "velocidad de recarga",
    "velocidad y control direccional moderados",
    "ventisca",
    "varias explosiones",
    "velocidad",
    "vórtice",
    "volátil",
    "volátiles",
    "volátiles daño aumentado"
]

export default frasesMX;